# Generated by Django 5.2.9 on 2026-01-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stok', models.IntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='barang/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_transaksi', models.CharField(max_length=50, unique=True)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('menunggu_pembayaran', 'Menunggu Pembayaran'), ('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='menunggu_pembayaran', max_length=20)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_pembayaran/')),
                ('alamat_pengiriman', models.TextField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailTransaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barang')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Keranjang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barang')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
