# Generated by Django 5.2.9 on 2026-01-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keranjang',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keranjang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detailtransaksi',
            name='transaksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_transaksi', to='api.transaksi'),
        ),
        migrations.AlterUniqueTogether(
            name='keranjang',
            unique_together={('user', 'barang')},
        ),
    ]
